### ISSUE TITLE
下载后直接运行 报错

### ISSUE THREAD

**Issue by Dan-0216** [PowerDos/electron-serialport#1]
下载后 直接 npm start  ,报了一个 这样的错误，如何解决？
`Uncaught Error: Module version mismatch. Expected 50, got 54.`

**Comment by PowerDos** [comment]
估计是electron的版本问题，我这个根据我但是电脑上的electron的版本编译的模块，只需要重新编译下模块就行(建议先删除node_modules)，详细的步骤可以参考https://github.com/PowerDos/serialport_electron_start

**Comment by Dan-0216** [comment]
我删除了node 包，然后重新 npm install , 安装完成后，我 npm start 启动项目，然后就直接报错了 
Error: A dynamic link library (DLL) initialization routine failed.
\\?\C:\Users\user\Desktop\seriport\electron-serialport-master (1)\electron-serialport-master\app\node_modules\_serialport@6.2.1@serialport\build\Release\serialport.node

现在的问题是 光是单单启动项目都报错，在浏览器的console 里面报了错，应该不管编译的事情

我删除了node 包，然后重新 npm install , 安装完成后，我 npm start 启动项目，然后就直接报错了 
Error: A dynamic link library (DLL) initialization routine failed.
\\?\C:\Users\user\Desktop\seriport\electron-serialport-master (1)\electron-serialport-master\app\node_modules\_serialport@6.2.1@serialport\build\Release\serialport.node

现在的问题是 光是单单启动项目都报错，在浏览器的console 里面报了错，应该不管编译的事情

**Comment by Dan-0216** [comment]
@PowerDos

**Comment by PowerDos** [comment]
我刚刚clone下来，用电脑的electron直接就可以跑起来了，我电脑的electron版本是v1.8.3。

electron串口编译经常会出现bug，因为串口模块的编译安装下来，是根据你电脑本机的node版本编译的，但在electron使用的话，需要编译成electron的node版本，大多数情况下，electron的node版本跟本机的node版本是不一样的。

你用的是什么操作系统

**Comment by Dan-0216** [comment]
你clone 下来后用什么命令跑起来的？ 不是npm start ? , 我用的是 win10 x64,node 版本为 8.11.3,electron 版本为1.14.3

**Comment by PowerDos** [comment]
进入app目录，执行`npm start`

**Comment by PowerDos** [comment]
done

**Comment by Echogithu** [comment]
> 你clone 下来后用什么命令跑起来的？ 不是npm start ? , 我用的是 win10 x64,node 版本为 8.11.3,electron 版本为1.14.3



> 下载后 直接 npm start ,报了一个 这样的错误，如何解决？
> `Uncaught Error: Module version mismatch. Expected 50, got 54.`

请问您的问题解决了吗？我也遇到同样的错误，可以请教您一下吗？谢谢
